# Docker-compose file for Wikitrivia

node:
  build: .
  links:
    - db:mongo
  ports:
    - "8000:8080"
  volumes:
    - .:/usr/src/app

data:
  image: mongo:3
  command: echo 'Data-only container'

db:
  image: mongo:3
  command: "mongod --smallfiles"
  volumes_from:
    - data
